// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmGoodUpload = `-- name: ConfirmGoodUpload :one
UPDATE media 
SET 
    bucket = $2,

    actual_content_type = $3,

    status = 'ready',

    size_bytes = $4,
    checksum = $5,
    metadata = $6,

    uploaded_at = NOW(),
    updated_at = NOW()
WHERE
    id = $1
RETURNING id
`

type ConfirmGoodUploadParams struct {
	ID                uuid.UUID   `json:"id"`
	Bucket            string      `json:"bucket"`
	ActualContentType pgtype.Text `json:"actual_content_type"`
	SizeBytes         pgtype.Int8 `json:"size_bytes"`
	Checksum          pgtype.Text `json:"checksum"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) ConfirmGoodUpload(ctx context.Context, arg ConfirmGoodUploadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, confirmGoodUpload,
		arg.ID,
		arg.Bucket,
		arg.ActualContentType,
		arg.SizeBytes,
		arg.Checksum,
		arg.Metadata,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO media (
  id,
  owner_username,
  file_name,

  purpose,
  bucket,
  object_key,

  declared_content_type
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id
`

type CreateUploadParams struct {
	ID                  uuid.UUID `json:"id"`
	OwnerUsername       string    `json:"owner_username"`
	FileName            string    `json:"file_name"`
	Purpose             string    `json:"purpose"`
	Bucket              string    `json:"bucket"`
	ObjectKey           string    `json:"object_key"`
	DeclaredContentType string    `json:"declared_content_type"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.ID,
		arg.OwnerUsername,
		arg.FileName,
		arg.Purpose,
		arg.Bucket,
		arg.ObjectKey,
		arg.DeclaredContentType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMediaById = `-- name: GetMediaById :one
SELECT id, purpose, bucket FROM media WHERE id=$1
`

type GetMediaByIdRow struct {
	ID      uuid.UUID `json:"id"`
	Purpose string    `json:"purpose"`
	Bucket  string    `json:"bucket"`
}

func (q *Queries) GetMediaById(ctx context.Context, id uuid.UUID) (GetMediaByIdRow, error) {
	row := q.db.QueryRow(ctx, getMediaById, id)
	var i GetMediaByIdRow
	err := row.Scan(&i.ID, &i.Purpose, &i.Bucket)
	return i, err
}

const updateUploadStatus = `-- name: UpdateUploadStatus :one
UPDATE media 
SET 
    status = $2,
    updated_at = NOW()
WHERE
    id = $1
RETURNING id
`

type UpdateUploadStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status StatusTypes `json:"status"`
}

func (q *Queries) UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateUploadStatus, arg.ID, arg.Status)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
