// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type StatusTypes string

const (
	StatusTypesPending  StatusTypes = "pending"
	StatusTypesUploaded StatusTypes = "uploaded"
	StatusTypesReady    StatusTypes = "ready"
	StatusTypesFailed   StatusTypes = "failed"
)

func (e *StatusTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusTypes(s)
	case string:
		*e = StatusTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusTypes: %T", src)
	}
	return nil
}

type NullStatusTypes struct {
	StatusTypes StatusTypes `json:"status_types"`
	Valid       bool        `json:"valid"` // Valid is true if StatusTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusTypes) Scan(value interface{}) error {
	if value == nil {
		ns.StatusTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusTypes), nil
}

type Medium struct {
	ID                  uuid.UUID          `json:"id"`
	OwnerUsername       string             `json:"owner_username"`
	FileName            string             `json:"file_name"`
	Purpose             string             `json:"purpose"`
	Bucket              string             `json:"bucket"`
	ObjectKey           string             `json:"object_key"`
	DeclaredContentType string             `json:"declared_content_type"`
	ActualContentType   pgtype.Text        `json:"actual_content_type"`
	Status              StatusTypes        `json:"status"`
	SizeBytes           pgtype.Int8        `json:"size_bytes"`
	Checksum            pgtype.Text        `json:"checksum"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	UploadedAt          pgtype.Timestamptz `json:"uploaded_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}
