// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfirmGoodUpload(ctx context.Context, arg ConfirmGoodUploadParams) (uuid.UUID, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (uuid.UUID, error)
	GetMediaById(ctx context.Context, id uuid.UUID) (GetMediaByIdRow, error)
	UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
