// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNews = `-- name: CreateNews :one
INSERT INTO news(
    media_id,
    creator_username,
    title,
    content
) VALUES (
    $1, $2, $3, $4
) RETURNING id
`

type CreateNewsParams struct {
	MediaID         uuid.UUID `json:"media_id"`
	CreatorUsername string    `json:"creator_username"`
	Title           string    `json:"title"`
	Content         string    `json:"content"`
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNews,
		arg.MediaID,
		arg.CreatorUsername,
		arg.Title,
		arg.Content,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createNewsWithPublishDate = `-- name: CreateNewsWithPublishDate :one
INSERT INTO news(
    creator_username,
    title,
    content,
    created_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id
`

type CreateNewsWithPublishDateParams struct {
	CreatorUsername string           `json:"creator_username"`
	Title           string           `json:"title"`
	Content         string           `json:"content"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateNewsWithPublishDate(ctx context.Context, arg CreateNewsWithPublishDateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNewsWithPublishDate,
		arg.CreatorUsername,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteNews = `-- name: DeleteNews :one
UPDATE news SET deleted_at=now() RETURNING id
`

func (q *Queries) DeleteNews(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteNews)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getNews = `-- name: GetNews :many
SELECT id, media_id, creator_username, title, content, created_at, updated_at, deleted_at FROM news WHERE created_at > $4 AND title ILIKE $1 AND content = $2 ORDER BY $3 ASC
`

type GetNewsParams struct {
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	Column3   interface{}      `json:"column_3"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetNews(ctx context.Context, arg GetNewsParams) ([]News, error) {
	rows, err := q.db.Query(ctx, getNews,
		arg.Title,
		arg.Content,
		arg.Column3,
		arg.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []News{}
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.CreatorUsername,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneNews = `-- name: GetOneNews :one
SELECT id, media_id, creator_username, title, content, created_at, updated_at, deleted_at FROM news WHERE id = $1
`

func (q *Queries) GetOneNews(ctx context.Context, id uuid.UUID) (News, error) {
	row := q.db.QueryRow(ctx, getOneNews, id)
	var i News
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.CreatorUsername,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateNews = `-- name: UpdateNews :one
UPDATE news
SET
    creator_username = COALESCE($1, creator_username),
    title = COALESCE($2, title),
    content = COALESCE($3, content)
WHERE
    id = $4
RETURNING id
`

type UpdateNewsParams struct {
	CreatorUsername pgtype.Text `json:"creator_username"`
	Title           pgtype.Text `json:"title"`
	Content         pgtype.Text `json:"content"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateNews(ctx context.Context, arg UpdateNewsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateNews,
		arg.CreatorUsername,
		arg.Title,
		arg.Content,
		arg.ID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
