// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNews(ctx context.Context, arg CreateNewsParams) (uuid.UUID, error)
	DeleteNews(ctx context.Context) (uuid.UUID, error)
	GetAllNews(ctx context.Context) (News, error)
	GetOneNews(ctx context.Context, id uuid.UUID) (News, error)
	UpdateNews(ctx context.Context, arg UpdateNewsParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
