// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service_auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_auth_proto protoreflect.FileDescriptor

const file_service_auth_proto_rawDesc = "" +
	"\n" +
	"\x12service_auth.proto\x12\x02pb\x1a\n" +
	"base.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_update_user.proto\x1a\x0frpc_login.proto2\xbb\x01\n" +
	"\vHavlabsAuth\x12=\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x00\x12=\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x00\x12.\n" +
	"\x05Login\x12\x10.pb.LoginRequest\x1a\x11.pb.LoginResponse\"\x00B'Z%github.com/daniel-bss/havlabs/auth/pbb\x06proto3"

var file_service_auth_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),  // 1: pb.UpdateUserRequest
	(*LoginRequest)(nil),       // 2: pb.LoginRequest
	(*CreateUserResponse)(nil), // 3: pb.CreateUserResponse
	(*UpdateUserResponse)(nil), // 4: pb.UpdateUserResponse
	(*LoginResponse)(nil),      // 5: pb.LoginResponse
}
var file_service_auth_proto_depIdxs = []int32{
	0, // 0: pb.HavlabsAuth.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.HavlabsAuth.UpdateUser:input_type -> pb.UpdateUserRequest
	2, // 2: pb.HavlabsAuth.Login:input_type -> pb.LoginRequest
	3, // 3: pb.HavlabsAuth.CreateUser:output_type -> pb.CreateUserResponse
	4, // 4: pb.HavlabsAuth.UpdateUser:output_type -> pb.UpdateUserResponse
	5, // 5: pb.HavlabsAuth.Login:output_type -> pb.LoginResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_auth_proto_init() }
func file_service_auth_proto_init() {
	if File_service_auth_proto != nil {
		return
	}
	file_base_proto_init()
	file_rpc_create_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_login_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_auth_proto_rawDesc), len(file_service_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_auth_proto_goTypes,
		DependencyIndexes: file_service_auth_proto_depIdxs,
	}.Build()
	File_service_auth_proto = out.File
	file_service_auth_proto_goTypes = nil
	file_service_auth_proto_depIdxs = nil
}
